name: Print Environment Variable

on:
  workflow_dispatch:

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
    - name: Print
      run: echo $MAVEN_USERNAME && echo $MAVEN_PASSWORD
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}